#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc config border_width	2
bspc config window_gap		12

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config normal_border_color "#252525"
bspc config active_border_color "#368aeb"
bspc config focused_border_color "#70b433"

bspc config focus_follows_pointer	true

# start desktop components
xset s 300 5 & XSECURELOCK_BLANK_TIMEOUT=15 XSECURELOCK_FONT="BlexMono Nerd Font:style=Regular" XSECURELOCK_SHOW_DATETIME=1 xss-lock -n /usr/lib/xsecurelock/dimmer -l -- xsecurelock & # screenlocker
~/.config/polybar/launch.sh & # bar
feh --bg-scale ~/.config/bspwm/wallpaper.jpg & # background
dunst & # notifications
picom & # compositor
xfce4-power-manager &
nm-applet
